# Importing Libraries

In [1]:
import uproot
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tqdm.notebook import tqdm
import pickle

# Loading Root Files Into Pandas Dataframes

In [2]:
f = uproot.open("data/checkout_MCC9.10_Run4c4d5_v10_04_07_13_BNB_NCpi0_overlay_surprise_reco2_hist_4c.root")
f.keys()

['lantern;1',
 'lantern/EventTree;1',
 'nuselection;1',
 'nuselection/NeutrinoSelectionFilter;1',
 'nuselection/SubRun;1',
 'proximity;1',
 'proximity/_clus_tree;1',
 'shrreco3d;1',
 'shrreco3d/_energy_tree;1',
 'shrreco3d/_dedx_tree;1',
 'shrreco3d/_rcshr_tree;1',
 'singlephotonana;1',
 'singlephotonana/vertex_tree;1',
 'singlephotonana/eventweight_tree;1',
 'singlephotonana/ncdelta_slice_tree;1',
 'singlephotonana/geant4_tree;1',
 'singlephotonana/true_eventweight_tree;1',
 'singlephotonana/pot_tree;1',
 'singlephotonana/run_subrun_tree;1',
 'wcpselection;1',
 'wcpselection/T_eval;1',
 'wcpselection/T_pot;1',
 'wcpselection/T_PFeval;1',
 'wcpselection/T_KINEvars;1',
 'wcpselection/T_BDTvars;1',
 'wcpselection/T_spacepoints;1']

In [3]:
already_printed_keys = []

for key in f["wcpselection"].items():
    key_name = key[0].split(";")[0]
    if key_name not in already_printed_keys: # sometimes a TTree is repeated, we ignore duplicates
        print("\nPrinting variables in TTree: ", key[0].split(";")[0])
        print(f["wcpselection"][key[0]].keys())
        already_printed_keys.append(key_name)

Printing variables in TTree:  T_eval
['run', 'subrun', 'event', 'flash_found', 'flash_time', 'flash_found_asInt', 'match_found_asInt', 'file_type', 'flash_measPe', 'flash_predPe', 'match_found', 'match_type', 'match_isFC', 'match_isTgm', 'match_notFC_FV', 'match_notFC_SP', 'match_notFC_DC', 'match_chargeU', 'match_chargeV', 'match_chargeY', 'match_energyY', 'light_mismatch', 'match_charge', 'match_energy', 'stm_eventtype', 'stm_lowenergy', 'stm_LM', 'stm_TGM', 'stm_STM', 'stm_FullDead', 'stm_clusterlength', 'lm_cluster_length', 'truth_nuEnergy', 'truth_energyInside', 'truth_electronInside', 'truth_nuPdg', 'truth_isCC', 'truth_isEligible', 'truth_NCisEligible', 'truth_isFC', 'truth_vtxInside', 'truth_vtxX', 'truth_vtxY', 'truth_vtxZ', 'truth_nuTime', 'match_completeness', 'match_completeness_energy', 'match_purity', 'match_purity_xz', 'match_purity_xy', 'weight_spline', 'weight_cv', 'weight_lee', 'weight_change']

Printing variables in TTree:  T_pot
['runNo', 'subRunNo', 'pot_tor875', 'pot_tor875good', 'spill_tor875', 'spill_tor875good', 'pass_ratio']

Printing variables in TTree:  T_PFeval
['run', 'subrun', 'event', 'neutrino_type', 'reco_nuvtxX', 'reco_nuvtxY', 'reco_nuvtxZ', 'reco_showervtxX', 'reco_showervtxY', 'reco_showervtxZ', 'reco_showerKE', 'reco_muonvtxX', 'reco_muonvtxY', 'reco_muonvtxZ', 'reco_muonMomentum', 'nuvtx_diff', 'showervtx_diff', 'muonvtx_diff', 'truth_corr_nuvtxX', 'truth_corr_nuvtxY', 'truth_corr_nuvtxZ', 'truth_corr_showervtxX', 'truth_corr_showervtxY', 'truth_corr_showervtxZ', 'truth_showerKE', 'truth_showerPdg', 'truth_showerMother', 'truth_corr_muonvtxX', 'truth_corr_muonvtxY', 'truth_corr_muonvtxZ', 'truth_muonvtxX', 'truth_muonvtxY', 'truth_muonvtxZ', 'truth_muonendX', 'truth_muonendY', 'truth_muonendZ', 'truth_muonMomentum', 'truth_nuEnergy', 'truth_energyInside', 'truth_electronInside', 'truth_nuPdg', 'truth_isCC', 'truth_vtxX', 'truth_vtxY', 'truth_vtxZ', 'truth_nuTime', 'truth_nuIntType', 'truth_NCDelta', 'truth_NprimPio', 'truth_pio_energy_1', 'truth_pio_energy_2', 'truth_pio_angle', 'truth_Npi0', 'truth_single_photon', 'truth_photon_angle', 'truth_photon_dis', 'evtDeltaTimeNS', 'evtTimeNS', 'reco_protonMomentum', 'reco_showerMomentum', 'reco_Nproton', 'truth_showerMomentum', 'mcflux_run', 'mcflux_evtno', 'mcflux_ndecay', 'mcflux_ntype', 'truth_nuScatType', 'mcflux_nuEnergy', 'mcflux_vx', 'mcflux_vy', 'mcflux_vz', 'mcflux_genx', 'mcflux_geny', 'mcflux_genz', 'mcflux_dk2gen', 'mcflux_gen2vtx', 'truth_nu_pos', 'truth_nu_momentum', 'truth_Ntrack', 'truth_id', 'truth_pdg', 'truth_process', 'truth_mother', 'truth_startXYZT', 'truth_endXYZT', 'truth_startMomentum', 'truth_endMomentum', 'truth_daughters', 'fMC_trackPosition', 'mc_isnu', 'mc_nGeniePrimaries', 'mc_nu_pdg', 'mc_nu_ccnc', 'mc_nu_mode', 'mc_nu_intType', 'mc_nu_target', 'mc_hitnuc', 'mc_hitquark', 'mc_nu_Q2', 'mc_nu_W', 'mc_nu_X', 'mc_nu_Y', 'mc_nu_Pt', 'mc_nu_Theta', 'mc_nu_pos', 'mc_nu_mom', 'reco_Ntrack', 'reco_id', 'reco_pdg', 'reco_process', 'reco_mother', 'reco_startXYZT', 'reco_endXYZT', 'reco_startMomentum', 'reco_endMomentum', 'reco_daughters', 'mcs_mu_tracklen', 'mcs_emu_tracklen', 'mcs_emu_MCS', 'mcs_ambiguity_MCS', 'reco_larpid_classified', 'reco_larpid_pdg', 'reco_larpid_proccess', 'reco_larpid_completeness', 'reco_larpid_purity', 'reco_larpid_pidScore_el', 'reco_larpid_pidScore_ph', 'reco_larpid_pidScore_mu', 'reco_larpid_pidScore_pi', 'reco_larpid_pidScore_pr', 'reco_larpid_procScore_prim', 'reco_larpid_procScore_ntrl', 'reco_larpid_procScore_chgd', 'reco_truthMatch_pdg', 'reco_truthMatch_id', 'reco_truthMatch_purity', 'reco_truthMatch_completeness', 'reco_truthMatch_nSimParts', 'reco_truthMatch_simPart_pdg', 'reco_truthMatch_simPart_purity', 'evtTimeNS_cor', 'cor_nu_time', 'cor_nu_time_nospill', 'cor_nu_time_spill', 'cor_nu_deltatime', 'Ph_Tot', 'PMT_ID', 'PMT_Time', 'PMT_Amp', 'PMT_TimeProp', 'PMT_TimeDP', 'PMT_TimeDL', 'PMT_Sat', 'RWM_Time', 'reco_sps_x', 'reco_sps_y', 'reco_sps_z', 'reco_sps_e', 'reco_sps_pdg', 'reco_sps_id']

Printing variables in TTree:  T_KINEvars
['kine_reco_Enu', 'kine_reco_add_energy', 'kine_energy_particle', 'kine_energy_info', 'kine_particle_type', 'kine_energy_included', 'kine_pio_mass', 'kine_pio_flag', 'kine_pio_vtx_dis', 'kine_pio_energy_1', 'kine_pio_theta_1', 'kine_pio_phi_1', 'kine_pio_dis_1', 'kine_pio_energy_2', 'kine_pio_theta_2', 'kine_pio_phi_2', 'kine_pio_dis_2', 'kine_pio_angle']

Printing variables in TTree:  T_BDTvars

## Choosing Variables To Load

In [4]:
T_bdt_vars = [              # variables involved with BDT training (if you want to train your own BDT, lots of these variables will be useful)
                            # many of these variables describe specific features of the WC spacepoints using this code: https://github.com/BNLIF/wire-cell-pid/blob/master/src/NeutrinoID_nue_tagger.h
                            # here, we just include higher level outputs:
    "nue_score",                    # BDT score for nue selection, used for the WC inclusive nueCC analysis
    "numu_score",                   # BDT score for numu selection, used for the WC inclusive numuCC selections
    "nc_delta_score",               # BDT score for NC Delta selection
    "nc_pio_score",                 # BDT score for NC pi0 selection
    "numu_cc_flag",                 # flag, -1 means not generic selected, 0 means generic selected, 1 means cut-based numuCC selected. We often use "numu_cc_flag >= 0" to apply generic neutrino selection.
]

T_eval_vars = [             # variables involved with low level reconstruction and truth information
    "run",                          # run number
    "subrun",                       # subrun number
    "event",                        # event number
    "match_isFC",                   # reconstructed cluster is fully contained (FC), boolean
    "truth_nuEnergy",               # true neutrino energy (MeV)
    "truth_nuPdg",                  # true neutrino pdg code
    "truth_isCC",                   # true interaction type is charged current, boolean
    "match_completeness_energy",    # the true energy deposited in the clusters that are 3D-matched with the reconstructed neutrino clusters (MeV)
    "truth_energyInside",           # the true energy deposited in the TPC Fiducial Volume (MeV)
    "truth_vtxInside",              # boolean, true neutrino vertex is inside the TPC Fiducial Volume
    "truth_vtxX",                   # true neutrino vertex x (cm)
    "truth_vtxY",                   # true neutrino vertex y (cm)
    "truth_vtxZ",                   # true neutrino vertex z (cm)
    "weight_cv",                    # untuned GENIE event weight
    "weight_spline",                # additional MicroBooNE Tune weight
]
T_eval_data_vars = [        # same as above, but for data files we do not attempt to load any truth information
    "run",
    "subrun",
    "event",
    "match_isFC",
]

T_kine_vars = [             # variables involved with kinematic reconstruction
    "kine_reco_Enu",                # reconstructed neutrino energy (MeV). "kine_reco_Enu > 0" is another way to apply generic neutrino selection.
    "kine_energy_particle",         # energy of each reco particle
    "kine_particle_type",           # pdg code of each reco particle
]

T_pf_vars = [               # variables involved with individual particles
    "truth_NprimPio",
    "truth_NCDelta",
    "reco_nuvtxX",
    "reco_nuvtxY",
    "reco_nuvtxZ",
    "reco_muonMomentum",            # reconstructed muon momentum 4-vector (p_x, p_y, p_z, p_t), in (GeV/c, GeV/c, GeV/c, GeV)

    # These variables are related to individual true particles
    "truth_Ntrack",
    "truth_id",
    "truth_pdg",
    "truth_mother",
    "truth_startMomentum",
    "truth_startXYZT",
    "truth_endXYZT",

    # These variables are related to individual reco particles
    "reco_Ntrack",
    "reco_id",
    "reco_pdg",
    "reco_mother",
    "reco_startMomentum",
    "reco_startXYZT",
    "reco_endXYZT",
]
T_pf_data_vars = [          # same as above, but for data files we do not attempt to load any truth information
    "reco_nuvtxX",
    "reco_nuvtxY",
    "reco_nuvtxZ",
    "reco_muonMomentum",
    "reco_Ntrack",
    "reco_id",
    "reco_pdg",
    "reco_mother",
    "reco_startMomentum",
    "reco_startXYZT",
    "reco_endXYZT",
]

## Making Dataframes

In [5]:
vars = {}
vars.update(f["wcpselection"]["T_BDTvars"].arrays(T_bdt_vars, library="np"))
vars.update(f["wcpselection"]["T_eval"].arrays(T_eval_vars, library="np"))
vars.update(f["wcpselection"]["T_KINEvars"].arrays(T_kine_vars, library="np"))
vars.update(f["wcpselection"]["T_PFeval"].arrays(T_pf_vars, library="np"))
nc_pi0_overlay_file_POT = np.sum(f["wcpselection"]["T_pot"].arrays("pot_tor875good", library="np")["pot_tor875good"])
for col in vars:
    vars[col] = vars[col].tolist()
all_df = pd.DataFrame(vars)
all_df["file"] = "nc_pi0_overlay_run4c"
print(f"loaded nc pi0 file, {len(all_df)} events, {nc_pi0_overlay_file_POT:.4e} POT")

loaded nc pi0 file, 57661 events, 3.3246e+21 POT

## Adding Extra Variables

In [6]:
# Extra reco variables
proton_nums = []
other_track_nums = []
energy_lists = all_df["kine_energy_particle"].to_numpy()
pdg_lists = all_df["kine_particle_type"].to_numpy()
for i in tqdm(range(all_df.shape[0]), desc="Adding extra WC reco particle variables"):
    proton_num = 0
    other_track_num = 0
    energy_list = energy_lists[i]
    pdg_list = pdg_lists[i]
    for i in range(len(energy_list)):
        if abs(pdg_list[i]) == 2212:
            if energy_list[i] > 35:
                proton_num += 1
        if abs(pdg_list[i]) == 13 or abs(pdg_list[i]) == 211: # see N_tracks at https://github.com/BNLIF/wcp-uboone-bdt/blob/main/inc/WCPLEEANA/cuts.h
            if energy_list[i] > 10.:
                other_track_num += 1
    proton_nums.append(proton_num)
    other_track_nums.append(other_track_num)
all_df["WC_reco_num_protons"] = proton_nums
all_df["WC_reco_num_other_tracks"] = other_track_nums

# Extra truth variables
max_prim_proton_energies = []
truth_pdgs = all_df["truth_pdg"].to_numpy()
truth_mothers = all_df["truth_mother"].to_numpy()
truth_startMomentums = all_df["truth_startMomentum"].to_numpy()
for i in tqdm(range(all_df.shape[0]), desc="Adding extra WC truth particle variables"):
    max_prim_proton_energy = 0
    truth_pdg_list = truth_pdgs[i]
    truth_mother_list = truth_mothers[i]
    truth_startMomentum_list = truth_startMomentums[i]
    if isinstance(truth_pdg_list, float) and np.isnan(truth_pdg_list):
        max_prim_proton_energies.append(-1)
        continue
    for j in range(len(truth_pdg_list)):
        if truth_mother_list[j] == 0 and truth_pdg_list[j] == 2212: # primary proton
            max_prim_proton_energy = max(truth_startMomentum_list[j][3] * 1000. - 938.272089, max_prim_proton_energy)
    max_prim_proton_energies.append(max_prim_proton_energy)
all_df["max_prim_proton_energy"] = max_prim_proton_energies

Adding extra WC reco particle variables:   0%|          | 0/57661 [00:00<?, ?it/s]

Adding extra WC truth particle variables:   0%|          | 0/57661 [00:00<?, ?it/s]

## Saving To Pickle

In [7]:
# Since these steps can take a while, especially if you use more files and pre-process more variables, 
# it can be useful to save this dataframe to a file so we don't have to re-make it every time we run this code.
# Usually when doing this, it's also worthwhile to drop variables that are not used, particularly PF variables which increase the file size a lot.

# Saving this takes a few minutes for this example, so here it's not actually helpful and we turn it off.
# If we were really using this, we'd add if statements to skip the earlier steps loading the root files when we load from pickle.

save_to_pickle = False
load_from_pickle = False

if save_to_pickle:
    with open("all_df.pkl", "wb") as f:
        pickle.dump(all_df, f)

if load_from_pickle:
    with open("all_df.pkl", "rb") as f:
        all_df = pickle.load(f)

In [12]:
all_df.query("kine_reco_Enu > 0 and match_isFC > 0 and nc_pio_score > 3 and WC_reco_num_protons > 1")

,nue_score,numu_score,nc_delta_score,nc_pio_score,numu_cc_flag,run,subrun,event,match_isFC,truth_nuEnergy,...,reco_id,reco_pdg,reco_mother,reco_startMomentum,reco_startXYZT,reco_endXYZT,file,WC_reco_num_protons,WC_reco_num_other_tracks,max_prim_proton_energy
25,-8.54142,-1.630076,1.194350,3.187934,0.0,21685,44,2202,True,423.433899,...,"[31031, 31000, 38013, 93028, 35010, 36011, 940...","[13, 11, 11, 11, 2212, 2212, 11, 22, 22, 2112,...","[0, 0, 38032, 93033, 35034, 36035, 94036, 0, 0...","[[-0.013244144, 0.0022702434, 0.045347765, 0.1...","[[180.92502, 36.756657, 256.90118, 0.0], [180....","[[180.04108, 36.255188, 260.23163, 0.0], [134....",nc_pi0_overlay_run4c,2,1,51.281065
102,-15.00000,-0.581482,-5.140738,3.363911,0.0,21692,177,8878,True,1764.497803,...,"[30001, 30004, 37027, 38028, 29006, 31008, 320...","[2212, 2212, 11, 11, 11, 11, 11, 2212, 11, 221...","[0, 0, 37031, 38032, 29033, 31034, 32035, 3303...","[[-0.4149785, 0.0049421755, 0.5057258, 1.14382...","[[104.06282, -94.81576, 843.0114, 0.0], [104.0...","[[89.19549, -94.341255, 865.44836, 0.0], [108....",nc_pi0_overlay_run4c,2,0,206.253320
137,-15.00000,-0.464565,-5.789953,3.747165,0.0,21688,10,542,True,1184.685913,...,"[28009, 28010, 26001, 27005, 40022, 30012, 340...","[2212, 2212, 11, 11, 11, 11, 11, 2212, 11, 111...","[0, 28009, 26025, 27026, 40027, 30028, 34029, ...","[[0.10615486, 0.29576194, 0.47654206, 1.098267...","[[166.95969, -76.76611, 222.75655, 0.0], [170....","[[170.44788, -68.29352, 237.84502, 0.0], [169....",nc_pi0_overlay_run4c,2,0,263.020903
201,-15.00000,-0.971947,-5.239707,3.254842,0.0,21688,279,13970,True,1048.705811,...,"[23001, 23005, 23048, 32016, 33018, 44042, 240...","[2212, 2212, 11, 11, 11, 11, 11, 11, 11, 11, 2...","[23005, 0, 23050, 32051, 33052, 44053, 24054, ...","[[0.14498834, 0.45440015, 0.07716621, 1.055372...","[[68.319984, -11.6046505, 612.84814, 0.0], [64...","[[70.41162, -1.8110809, 614.4037, 0.0], [68.31...",nc_pi0_overlay_run4c,2,0,120.536357
269,-15.00000,-0.544593,-3.307960,3.617759,0.0,21697,31,1589,True,1344.557007,...,"[47001, 47002, 47003, 47027, 50011, 54014, 108...","[2212, 2212, 2212, 11, 11, 11, 11, 2212, 11, 1...","[47002, 0, 47002, 0, 50028, 54029, 108030, 490...","[[-0.27210593, 0.3348395, 0.3164917, 1.0801299...","[[94.199715, 47.598663, 409.33752, 0.0], [95.0...","[[87.22259, 56.004425, 418.17383, 0.0], [94.19...",nc_pi0_overlay_run4c,3,0,343.124181
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57244,-15.00000,-0.939413,-4.011004,3.457103,0.0,21365,188,9417,True,1539.947876,...,"[26000, 26001, 28010, 29015, 30018, 31019, 320...","[2212, 2212, 11, 11, 2212, 2212, 11, 11, 111, ...","[0, 0, 28031, 29032, 30033, 31034, 32035, 3803...","[[0.25783524, -0.44695228, 0.14737782, 1.08088...","[[36.86821, -95.73934, 233.1292, 0.0], [36.868...","[[45.48683, -106.57174, 237.64165, 0.0], [42.1...",nc_pi0_overlay_run4c,2,0,145.465523
57264,-15.00000,-1.312968,-8.502112,4.696887,0.0,21365,279,13982,True,1389.613159,...,"[22010, 23013, 19006, 21009, 26021, 27022, 280...","[2212, 11, 11, 2212, 211, 11, 2212, 11, 11, 11...","[0, 23034, 19035, 21036, 26037, 27038, 28039, ...","[[0.011676151, 0.06807301, -0.26814535, 0.9782...","[[151.8742, -37.4364, 863.75, 0.0], [161.06448...","[[152.0493, -37.51691, 861.3285, 0.0], [243.32...",nc_pi0_overlay_run4c,2,0,54.038375
57355,-15.00000,-0.592741,-2.300750,3.104860,0.0,21366,254,12709,True,1138.285400,...,"[37015, 37026, 34011, 39022, 38017, 40023, 750...","[2212, 2212, 11, 11, 11, 2212, 2212, 22, 22, 2...","[0, 0, 34027, 39028, 38029, 40030, 75031, 0, 0...","[[0.09470888, 0.29190803, 0.2673928, 1.0227576...","[[76.064476, 89.37172, 166.51433, 0.0], [76.06...","[[76.657394, 91.57066, 169.28769, 0.0], [77.03...",nc_pi0_overlay_run4c,2,0,71.107775
57357,-15.00000,-0.320297,-5.400332,3.397971,0.0,21366,254,12724,True,1025.246704,...,"[43014, 43016, 46024, 45022, 44017, 51029, 460...","[2212, 2212, 11, 11, 2212, 11, 111, 22, 22, 21...","[0, 0, 46037, 45038, 44039, 51040, 0, 46036, 4...","[[0.22226755, 0.13472924, 0.5819784, 1.1342875...","[[22.214703, -74.539406, 1009.3705, 0.0], [22....","[[30.65076, -68.758095, 1031.735, 0.0], [18.49...",nc_pi0_overlay_run4c,2,0,342.633754
57403,-15.00000,-0.361887,-4.320400,3.697170,0.0,21366,386,19319,True,1445.904785,...,"[41012, 41013, 40004, 43024, 49037, 47035, 480...","[2212, 2212, 11, 11, 11, 11, 2212, 2212, 22, 2...","[41013, 0, 40043, 43044, 49045, 47046, 48047, ...","[[-0.14502244, 0.12444023, 0.43614075, 1.05218...","[[207.32475, -50.983166, 128.15947, 0.0], [207...","[[204.46411, -48.268932, 136.99673, 0.0], [210...",nc_pi0_overlay_run4c,2,0,128.999620

# Particle-level Information

In [13]:
# A lot of the information in these files comes from detailed processing of raw WC spacepoints, which are not saved in these files.
# We do save some basic information about each WC reco particle. 
# This type of information is the input to the new RNN-based energy estimator: https://arxiv.org/abs/2406.10123

# Let's look at one event, passing the WC NC Pi0 selection:

one_event_df = all_df.query("file=='nc_pi0_overlay_run4c' and run==21692 and subrun==177 and event==8878")
print("High-level information:")
display(one_event_df[["file", "run", "subrun", "event", "kine_reco_Enu", "truth_nuEnergy", "nue_score", "numu_score", "nc_delta_score", "nc_pio_score"]])

print("Reconstructed particles:")
display(one_event_df[["reco_Ntrack", "reco_id", "reco_mother", "reco_pdg", "reco_startMomentum", "reco_startXYZT", "reco_endXYZT"]])

# reco_Ntrack shows us that we have 13 reconstructed particles, so each variable is a vector of length 13. 
# Each of these has an id and a mother, which form a tree structure. Each of these has a reco pdg describing the type of particle,
# a reco momentum 4-vector describing the reconstructed energy and direction, and a reco start and end XYZT 4-vector, which give the reconstructed position and time.

# We also have the same information for truth particles:

print("True particles:")
display(one_event_df[["truth_Ntrack", "truth_id", "truth_pdg", "truth_mother", "truth_startMomentum", "truth_startXYZT", "truth_endXYZT"]])

# There is even more information in the files, for example truth_process that can tell you more about what process created a particle, but we won't use that in this tutorial.

High-level information:

,file,run,subrun,event,kine_reco_Enu,truth_nuEnergy,nue_score,numu_score,nc_delta_score,nc_pio_score
102,nc_pi0_overlay_run4c,21692,177,8878,493.773621,1764.497803,-15.0,-0.581482,-5.140738,3.363911

Reconstructed particles:

,reco_Ntrack,reco_id,reco_mother,reco_pdg,reco_startMomentum,reco_startXYZT,reco_endXYZT
102,21,"[30001, 30004, 37027, 38028, 29006, 31008, 320...","[0, 0, 37031, 38032, 29033, 31034, 32035, 3303...","[2212, 2212, 11, 11, 11, 11, 11, 2212, 11, 221...","[[-0.4149785, 0.0049421755, 0.5057258, 1.14382...","[[104.06282, -94.81576, 843.0114, 0.0], [104.0...","[[89.19549, -94.341255, 865.44836, 0.0], [108...."

True particles:

,truth_Ntrack,truth_id,truth_pdg,truth_mother,truth_startMomentum,truth_startXYZT,truth_endXYZT
102,126,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 15, 16...","[14, 2212, 2112, 111, 2212, 2112, 2112, 2112, ...","[0, 0, 0, 0, 0, 0, 0, 0, 8, 8, 8, 8, 8, 7, 7, ...","[[0.10528809, 0.439422, 0.6261246, 0.7721459],...","[[104.20679, -94.843956, 842.8466, 3724.4985],...","[[12466.667, 51359.918, 74163.0, 6740.566], [8..."

# Particle-level Trees

In [14]:
from particle import Particle

def print_particle_tree(curr_id, ids, mothers, pdgs, start_momentums, spaces=""):
    for i in range(len(ids)):
        if ids[i] == curr_id: # found current particle
            name = Particle.from_pdgid(pdgs[i]).name
            energy = start_momentums[i][3]*1000
            mass = Particle.from_pdgid(pdgs[i]).mass
            if mass == None:
                mass = 0
            KE = energy - mass
            print(f"{spaces}{name} {KE:.2f} MeV")
            for j in range(len(pdgs)):
                if mothers[j] == curr_id: # found daughter particle
                    print_particle_tree(ids[j], ids, mothers, pdgs, start_momentums, spaces + "    ")

def print_particle_trees(event_df, reco=True, truth=True):
    for event_i in range(event_df.shape[0]):
        row = event_df.iloc[event_i]
        reco_ids = row["reco_id"]
        reco_mothers = row["reco_mother"]
        reco_pdgs = row["reco_pdg"]
        reco_start_momentums = row["reco_startMomentum"]
        truth_ids = row["truth_id"]
        truth_mothers = row["truth_mother"]
        truth_pdgs = row["truth_pdg"]
        truth_start_momentums = row["truth_startMomentum"]
        if reco:
            print("Reconstructed Particle Tree:\n")
            for particle_i in range(len(reco_ids)):
                if reco_mothers[particle_i] == 0:
                    print_particle_tree(reco_ids[particle_i], reco_ids, reco_mothers, reco_pdgs, reco_start_momentums)
        if truth:
            print("\nTruth Particle Tree:\n")
            for particle_i in range(len(truth_ids)):
                if truth_mothers[particle_i] == 0:
                    print_particle_tree(truth_ids[particle_i], truth_ids, truth_mothers, truth_pdgs, truth_start_momentums)

print_particle_trees(one_event_df, reco=True, truth=True)

Reconstructed Particle Tree:

p 205.56 MeV
    gamma 6.18 MeV
        e- 6.18 MeV
p 96.84 MeV
pi0 116.98 MeV
    gamma 99.20 MeV
        e- 99.20 MeV
            gamma 7.78 MeV
                e- 7.78 MeV
    gamma 50.81 MeV
        e- 50.81 MeV
            gamma 1.33 MeV
                e- 1.33 MeV
            n 3.06 MeV
                p 3.06 MeV
            gamma 1.90 MeV
                e- 1.90 MeV
            n 2.02 MeV
                p 2.02 MeV
gamma 1.91 MeV
    e- 1.91 MeV

Truth Particle Tree:

nu(mu) 772.15 MeV
p 206.25 MeV
n 21.50 MeV
    Ar40 -8.53 MeV
    n 5.87 MeV
        n 2.43 MeV
            Ar40 -9.08 MeV
            Ar40 -9.01 MeV
            Ar40 -8.99 MeV
            n 0.18 MeV
            Ar40 -9.12 MeV
        Ar40 -8.79 MeV
    n 1.94 MeV
        Ar40 -9.02 MeV
        Ar40 -9.06 MeV
        n 0.27 MeV
        Ar40 -9.11 MeV
    Ar39 -8.63 MeV
pi0 35.77 MeV
    gamma 61.39 MeV
        e- 54.08 MeV
            gamma 10.27 MeV
    gamma 109.36 MeV
        e- 24.23 MeV
        e+ 84.11 MeV
            gamma 16.18 MeV
p 101.64 MeV
n 75.74 MeV
    Ar40 -9.08 MeV
    Ar40 -9.07 MeV
    n 10.23 MeV
        Ar40 -9.11 MeV
        n 1.54 MeV
            p 0.94 MeV
            p 0.44 MeV
        Ar40 -8.71 MeV
    n 4.24 MeV
        Ar40 -9.11 MeV
        Ar40 -9.08 MeV
        n 1.40 MeV
            O16 -3.97 MeV
            Ar40 -9.08 MeV
            Ar40 -9.10 MeV
            Ar40 -9.10 MeV
            Ar40 -9.10 MeV
        Ar40 -9.07 MeV
    n 4.19 MeV
        Ar40 -8.97 MeV
        n 0.42 MeV
        Ar40 -9.02 MeV
    p 2.84 MeV
    n 1.97 MeV
        Ar40 -9.03 MeV
        Ar40 -9.06 MeV
        Ar40 -9.09 MeV
        Ar40 -9.07 MeV
        Ar40 -9.06 MeV
        Ar40 -9.10 MeV
        Ar40 -9.11 MeV
        Ar40 -9.10 MeV
    n 1.15 MeV
        Ar40 -9.09 MeV
    Cl35 -6.15 MeV
n 53.02 MeV
    Ar40 -8.62 MeV
    Ar40 -9.11 MeV
    Ar40 -9.11 MeV
    Ar40 -9.06 MeV
    Ar40 -8.98 MeV
    n 2.57 MeV
n 232.70 MeV
    n 164.29 MeV
        n 109.52 MeV
            Ar40 -9.00 MeV
            Ar40 -9.08 MeV
        n 40.36 MeV
            n 5.51 MeV
                Ar40 -9.06 MeV
                Ar40 -9.02 MeV
                Ar40 -9.02 MeV
                Ar40 -9.09 MeV
                Ar40 -8.90 MeV
                n 1.27 MeV
                    Ar40 -9.09 MeV
                    Ar40 -9.08 MeV
                    Ar40 -9.11 MeV
                    Ar40 -9.11 MeV
                Ar40 -9.02 MeV
            n 1.83 MeV
                Ar40 -9.07 MeV
                Ar40 -9.07 MeV
                Ar40 -9.12 MeV
                n 0.64 MeV
                Ar40 -9.13 MeV
            n 1.45 MeV
                Ar40 -9.06 MeV
                Ar40 -9.08 MeV
                Ar40 -9.09 MeV
                Ar40 -9.10 MeV
            n 0.22 MeV
            Ar37 -7.14 MeV
        Ar39 -8.93 MeV
    n 30.33 MeV
        p 21.54 MeV
        Cl40 -8.31 MeV
    n 3.32 MeV
        Ar40 -9.11 MeV
        n 1.63 MeV
            Ar40 -9.08 MeV
            Ar40 -9.09 MeV
            Ar40 -9.08 MeV
            Ar40 -9.07 MeV
            Ar40 -9.09 MeV
            Ar40 -9.09 MeV
            Ar40 -9.11 MeV
        Ar40 -9.10 MeV
    n 1.80 MeV
        Ar40 -9.09 MeV
        Ar40 -9.07 MeV
        Ar40 -9.07 MeV
        Ar40 -9.10 MeV
        Ar40 -9.07 MeV
        Ar40 -9.08 MeV
        Ar40 -9.10 MeV
        Ar40 -9.11 MeV
    Ar37 -8.51 MeV

# Spacepoints

## Backtracking

# WC PMT Info

# BEE Event Displays

Beyond the scope of this tutorial. But here's an example to try playing around with:

https://www.phy.bnl.gov/twister/bee/set/uboone/reco/2021-01/pr-1/event/3/ (publicly advertised already, from https://microboone.fnal.gov/wp-content/uploads/MICROBOONE-NOTE-1100-PUB-1.pdf figure 5).

And here's a reference explaining how to make your own BEE event displays:

celltree to BEE (for reconstructed particles): https://docs.google.com/document/d/1jNmBqXuNngZk4sPqk8Ps87_bPqZinXL5_IeFC5Xb6vs/edit#heading=h.s8ydywlelr5i

artroot to BEE (for truth particles): https://docs.google.com/document/d/1T-__tCrazXoLGUeJ5ol4xlGKHMxlepX2sDVy3ufMt8g/edit

# Adding Systematics

Beyond the scope of this tutorial. Much more work to set up and run than everything else here, but here are some references for how you might get started, but it's probably easiest to talk to WC people for help with this.

Generally uses https://github.com/BNLIF/LEEana and https://github.com/BNLIF/wcp-uboone-bdt.

Xin's summary of analysis steps: https://www.phy.bnl.gov/xqian/talks/wire-cell/LEEana/readme

Hanyu's tutorial video: https://indico.bnl.gov/event/10045/
  
Hanyu's and Xiangpan's tutorial google doc: https://docs.google.com/document/d/1sgr_OBzNYnGG1qi1mX_wIUHIPJDSDRetNSzmcZQk9Ik/edit

TLee tutorial google doc: https://docs.google.com/document/d/1dqo7GFlz8g85D-lsjlqZRP57avBI2dDq6S8VMANAr-Q/edit#heading=h.ldw9jixqbcg0edit#heading=h.ldw9jixqbcg0